[workspace]
revolver = "2"

# Rust package
members = [
    "lakestream",
    "lakestream-cli",
    "lakestream-web",
]

# Python interface to lakestream
# exclude to prevent publishing to crates.io
exclude = [
    "lakestream-py",
]

[profile.release]
lto = true
opt-level = "z"
debug = false
rpath = false
