[package]
name = "lakestream-web"
# version is auto-updated via lakestream/build.rs
version = "0.0.3-alpha"
edition = "2021"

[dependencies]
lakestream = { path = "../lakestream" }
leptos = { version = "0.2.5"}
console_log = "1"
log = "0.4.17"
console_error_panic_hook = "0.1.7"

[dev-dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3.0"
web-sys = "0.3"
